In [18]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
# a[0,1]
p = [0.0 for _ in range(3)]
print(np.tile(a,(3,1)))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
import numpy as np
import sys
sys.path.append("..")
from MPC_Controller.common.Quadruped import Quadruped, RobotType
from MPC_Controller.common.LegController import computeLegJacobianAndPosition

quad = Quadruped(RobotType.ALIENGO)
q = np.zeros((3,1), dtype=np.float32)
J, p = computeLegJacobianAndPosition(quad, q, 2)

print("J:\n",J)
print("p:\n",p)

J:
 [[ 0.     0.404  0.195]
 [ 0.404 -0.    -0.   ]
 [-0.066  0.     0.   ]]
p:
 [[ 0.   ]
 [-0.066]
 [-0.404]]


In [1]:
import numpy as np
a = np.zeros((13*10,13))
print(np.exp(a))
print(np.zeros(12))

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
import numpy as np
import quaternion
q = np.quaternion(1,2,3,4)
print(q.z)

4.0


In [1]:
import numpy as np

def test(hhhh:np.ndarray):
    return hhhh

test(np.zeros((3,3)))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [1]:
from MPC_Controller.FSM_States.ControlFSMData import ControlFSMData
print(ControlFSMData())

In [2]:
x = np.min([np.max([10, -0.25]), 0.25])
print(x)

0.25


In [42]:
import numpy as np
from time import time
a = np.zeros((3,1), dtype=np.float32)
b = np.array([3.0,4,5]).reshape((3,1))

t = time()
a = b.copy()
# np.copyto(a, b, casting="same_kind")

print(time()-t)
a[0] = 0
print(b)

0.0
4


In [39]:
a = [0 for _ in range(4)]
b = [1, 2, 3]
a[:] = b

print(a)

[1, 2, 3]


In [2]:
from cvxopt import matrix
import numpy as np
q = np.array([1,2,3.0], dtype=np.float64).reshape(3,1)
print(matrix(q))

[ 1.00e+00]
[ 2.00e+00]
[ 3.00e+00]



In [24]:
list1 = [3, 4, 5, 8]
list2 = [5, 6, 7]

print(id(list1))
print(id(list2))

list1[:] = list2
# list1 = list2[:]


list1[0] = 0
print(id(list1))
print(id(list2))
print(list1[1] is list2[1])

140126302247264
140126801388000
140126302247264
140126801388000
True


In [5]:
import numpy as np
import quaternion
q = np.quaternion(1,0,0,0)
print(type(quaternion.as_euler_angles(q)))

<class 'numpy.ndarray'>
