In [18]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
# a[0,1]
p = [0.0 for _ in range(3)]
print(np.tile(a,(3,1)))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [1]:
import numpy as np
a = np.zeros((13*10,13))
print(np.exp(a))
print(np.zeros(12))

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [1]:
import numpy as np

def test(hhhh:np.ndarray):
    return hhhh

test(np.zeros((3,3)))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [2]:
x = np.min([np.max([10, -0.25]), 0.25])
print(x)

0.25


In [42]:
import numpy as np
from time import time
a = np.zeros((3,1), dtype=np.float32)
b = np.array([3.0,4,5]).reshape((3,1))

t = time()
a = b.copy()
# np.copyto(a, b, casting="same_kind")

print(time()-t)
a[0] = 0
print(b)

0.0
4


In [39]:
a = [0 for _ in range(4)]
b = [1, 2, 3]
a[:] = b

print(a)

[1, 2, 3]


In [2]:
from cvxopt import matrix
import numpy as np
q = np.array([1,2,3.0], dtype=np.float64).reshape(3,1)
print(matrix(q))

[ 1.00e+00]
[ 2.00e+00]
[ 3.00e+00]



In [24]:
list1 = [3, 4, 5, 8]
list2 = [5, 6, 7]

print(id(list1))
print(id(list2))

list1[:] = list2
# list1 = list2[:]


list1[0] = 0
print(id(list1))
print(id(list2))
print(list1[1] is list2[1])

140126302247264
140126801388000
140126302247264
140126801388000
True


In [12]:
import numpy as np
a = np.array([0,-1,-1,0], dtype=np.float32)
b = np.array([0,0,0,0], dtype=np.float32)
print(a,b)
for m,n in zip(a,b):
    print(m/n)

[ 0. -1. -1.  0.] [0. 0. 0. 0.]
nan
-inf
-inf
nan


/home/silvery/anaconda3/envs/rlmpc/lib/python3.7/site-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in float_scalars
  
/home/silvery/anaconda3/envs/rlmpc/lib/python3.7/site-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in float_scalars
  


In [1]:
import numpy as np
a = np.zeros((4,3,1))

a[0]

array([[0.],
       [0.],
       [0.]])

In [18]:
import torch
import numpy as np
checkpoint = torch.load("../RL_Environment/runs/Aliengo/nn/Aliengo.pth")


In [17]:
model = checkpoint['model']
# print(model)
for key in checkpoint.keys():
    print(key)
print()
for key in model.keys():
    print(key)
# checkpoint["model"]

running_mean_std
reward_mean_std
scaler
model
epoch
optimizer
frame
last_mean_rewards
env_state

a2c_network.sigma
a2c_network.actor_mlp.0.weight
a2c_network.actor_mlp.0.bias
a2c_network.actor_mlp.2.weight
a2c_network.actor_mlp.2.bias
a2c_network.actor_mlp.4.weight
a2c_network.actor_mlp.4.bias
a2c_network.value.weight
a2c_network.value.bias
a2c_network.mu.weight
a2c_network.mu.bias


In [33]:
l1 = [1, 1, 3.0, 4, 1]
print(all(val>=0 for val in l1))

True
