In [1]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
# a[0,1]
p = [0.0 for _ in range(3)]
print(np.tile(a,(3,1)))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
import numpy as np
a = np.zeros((13*10,13))
print(np.exp(a))
print(np.zeros(12))

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
import numpy as np

def test(hhhh:np.ndarray):
    return hhhh

test(np.zeros((3,3)))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
x = np.min([np.max([10, -0.25]), 0.25])
print(x)

0.25


In [5]:
import numpy as np
from time import time
a = np.zeros((3,1), dtype=np.float32)
b = np.array([3.0,4,5]).reshape((3,1))

t = time()
a = b.copy()
# np.copyto(a, b, casting="same_kind")

print(time()-t)
a[0] = 0
print(b)

4.7206878662109375e-05
[[3.]
 [4.]
 [5.]]


In [6]:
a = [0 for _ in range(4)]
b = [1, 2, 3]
a[:] = b

print(a)

[1, 2, 3]


In [7]:
from cvxopt import matrix
import numpy as np
q = np.array([1,2,3.0], dtype=np.float64).reshape(3,1)
print(matrix(q))

[ 1.00e+00]
[ 2.00e+00]
[ 3.00e+00]



In [8]:
list1 = [3, 4, 5, 8]
list2 = [5, 6, 7]

print(id(list1))
print(id(list2))

list1[:] = list2
# list1 = list2[:]


list1[0] = 0
print(id(list1))
print(id(list2))
print(list1[1] is list2[1])

139883324615328
139883324614288
139883324615328
139883324614288
True


In [9]:
import numpy as np
a = np.array([0,-1,-1,0], dtype=np.float32)
b = np.array([0,0,0,0], dtype=np.float32)
print(a,b)
for m,n in zip(a,b):
    print(m/n)

[ 0. -1. -1.  0.] [0. 0. 0. 0.]
nan
-inf
-inf
nan


/home/silvery/anaconda3/envs/rlmpc/lib/python3.7/site-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in float_scalars
  
/home/silvery/anaconda3/envs/rlmpc/lib/python3.7/site-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in float_scalars
  


In [10]:
import numpy as np
a = np.zeros((4,3,1))

a[0]

array([[0.],
       [0.],
       [0.]])

In [11]:
import torch
import numpy as np
checkpoint = torch.load("../RL_Environment/runs/Aliengo/nn/Aliengo.pth")


In [ ]:
model = checkpoint['model']
# print(model)
for key in checkpoint.keys():
    print(key)
print()
for key in model.keys():
    print(key)
# checkpoint["model"]

In [13]:
l1 = [1, 1, 3.0, 4, 1]
print(all(val>=0 for val in l1))

True


In [20]:
import numpy as np
ones = np.array([1,2,3,4,5,6,7,8,9]).reshape((3,3))
vec_h = np.ones(3)*2
vec_w = np.ones((3,1))*2

print(ones)
print(vec_h)
print(vec_w)
print(ones @ vec_h)
print(ones @ vec_w)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2. 2. 2.]
[[2.]
 [2.]
 [2.]]
[12. 30. 48.]
[[12.]
 [30.]
 [48.]]


In [36]:
import torch

t1 = torch.tensor([1,2,3,4,5,6,7,8,9]).reshape((3,3))
t2 = torch.tensor([2,2,2])#.unsqueeze(1)

# print(t1 * t2)
torch.mul(t1, t2)

t1_gpu = t1.to("cuda")
print(t1_gpu.device)
t1_d = t1_gpu.detach()
print(t1_d)
var = torch.nn.functional.pad(t2, (0, 1),mode="constant", value=0)
print(var)

cuda:0
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], device='cuda:0')
tensor([2, 2, 2, 0])


In [30]:
import sys
sys.path.append("..")
from MPC_Controller.common.Quadruped import RobotType
[name.title() for name in RobotType.__members__.keys()]
# print(RobotType.name) 

['Aliengo', 'Mini_Cheetah', 'Xiaotian', 'Anymal', 'A1']

In [2]:
from isaacgym import gymapi

gymapi.Vec3(*[1,2,3])

<isaacgym._bindings.linux-x86_64.gym_37.Vec3 at 0x7f091702cfb0>

In [17]:
import sys
sys.path.append("..")
from MPC_Controller.utils import *
from MPC_Controller.math_utils.orientation_tools import *
q = Quaternion(0.5,0,1,0)

print(q)
print(q.unit())
# print(q.conjugate())
# print(q.inverse())

test_rot = quat_to_rot(q)
print(test_rot)
print(test_rot.T)
print(rot_to_quat(test_rot.T))

q2 = Quaternion(1,2,3,4)
print(quat_product(q2.unit(), q.unit())._norm)

[0.5, 0.0, 1.0, 0.0]
[0.44716157205240176, 0.0, 0.8943231441048035, 0.0]
[[-1.  0. -1.]
 [ 0.  1.  0.]
 [ 1.  0. -1.]]
[[-1.  0.  1.]
 [ 0.  1.  0.]
 [-1.  0. -1.]]
[-0.5, 0.0, 1.0, 0.0]
1.194
