In [18]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
# a[0,1]
p = [0.0 for _ in range(3)]
print(np.tile(a,(3,1)))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
import numpy as np
from quadruped import Quadruped
from kinematics import computeLegJacobianAndPosition

quad = Quadruped()
q = np.zeros((3,1), dtype=np.float32)
J, p = computeLegJacobianAndPosition(quad, q, 2)

print("J\n",J)

print("p\n",p)

J
 [[ 0.          0.40399998  0.19499999]
 [ 0.40399998 -0.         -0.        ]
 [-0.066       0.          0.        ]]
p
 [[ 0.        ]
 [-0.066     ]
 [-0.40399998]]


In [1]:
import numpy as np
a = np.zeros((13*10,13))
print(np.exp(a))

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
